### ISSUE TITLE
problem with gnome 3.16

### ISSUE THREAD

**Issue by Bersam** [lvillani/i3-gnome#3]
Hi!
I'm using this session with small changes for Archlinux (https://aur.archlinux.org/packages/i3-gnome/), but in the last update (gnome 3.16) it doesn't work anymore (i3 without gnome works fine).
@joehillen traced this and noticed this segfault here:
https://gist.github.com/joehillen/42e933d293d52b2c1370
do you have any idea what the problem could be?

**Comment by lvillani** [comment]
I guess it's a weird interaction between the startup script and logind. Unfortunately I don't have easy access to a machine with systemd/logind and Gnome 3.6 at the moment.

**Comment by lvillani** [comment]
If you come by any solution or workaround let me know so that I can patch it.

**Comment by joehillen** [comment]
My impression is that the problem is not caused by i3-gnome. i3-gnome doesn't do anything unusual. The problem is with gdm. It should never segfault, no matter what crazy configuration you have. 

My workaround has been to go back booting up regular i3 and adding this to the beginning of my config:

    exec --no-startup-id /usr/lib/gnome-settings-daemon/gnome-settings-daemon

It doesn't work as well as i3-gnome did, but it's a start.

**Comment by enricostano** [comment]
same issue here, this is what I get from the journal:

```
abr 20 17:03:26 archlap systemd[1]: Started Locale Service.
abr 20 17:04:57 archlap gnome-session[2152]: WARNING: Application 'i3-gnome.desktop' failed to register before timeout
abr 20 17:04:57 archlap gnome-session[2152]: Unrecoverable failure in required component i3-gnome.desktop
abr 20 17:04:57 archlap gnome-session[2152]: gnome-session[2152]: WARNING: Application 'i3-gnome.desktop' failed to register before timeout
abr 20 17:04:57 archlap gnome-session[2152]: Entering running state
abr 20 17:04:57 archlap gnome-session[2152]: Failed to play sound: File or data not found
abr 20 17:05:09 archlap gnome-session[2152]: gnome-session[2152]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
abr 20 17:05:09 archlap gnome-session[2152]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
abr 20 17:05:09 archlap gnome-session[2152]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
abr 20 17:05:09 archlap gnome-session[2152]: gnome-session[2152]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
abr 20 17:05:09 archlap gnome-session[2152]: gnome-session[2152]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
abr 20 17:05:09 archlap gnome-session[2152]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
abr 20 17:05:09 archlap gnome-session[2152]: gnome-session[2152]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
abr 20 17:05:09 archlap gnome-session[2152]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
abr 20 17:05:09 archlap gnome-session[2152]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
abr 20 17:05:09 archlap gnome-session[2152]: gnome-session[2152]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
abr 20 17:05:09 archlap gnome-session[2152]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
abr 20 17:05:09 archlap gnome-session[2152]: gnome-session[2152]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
abr 20 17:05:09 archlap gnome-session[2152]: ** (gnome-session-quit:2442): WARNING **: Failed to call logout: GDBus.Error:org.gnome.SessionManager.NotInRunning: Logout in
abr 20 17:05:09 archlap slim[2137]: pam_unix(slim:session): session closed for user enrico
```
https://gist.github.com/enricostano/73fa78af75b0d70c731b

**Comment by enricostano** [comment]
I found a possibly related [bug track](https://bugs.archlinux.org/task/44548) in Arch Linux bug tracker. Although I'm not sure it's related.

**Comment by lvillani** [comment]
Is someone having the same problem on Gnome 3.16 on the latest Ubuntu? I have some spare time to setup an Ubuntu VM but not enough time to perform a full installation of Arch.

**Comment by lvillani** [comment]
Oh, don't worry. Ubuntu 15.04 still ships with Gnome 3.14. I don't have means to test Gnome 3.16 without investing a lot of time at the moment.

**Comment by rvlander** [comment]
I am impacted by this problem too.

[Antergos](http://antergos.com/) will offer you an easy installation process for Arch.

**Comment by rvlander** [comment]
I filed a bug on GNOME Bugzilla:
[https://bugzilla.gnome.org/show_bug.cgi?id=748445](https://bugzilla.gnome.org/show_bug.cgi?id=748445)

**Comment by REALDrummer** [comment]
This bug is affecting me as well, and not just on GNOME 3.16. I have the same issue with GNOME 3.18. I tried 3.16 with i3 4.11 and I tried GNOME 3.18 with i3 versions 4.11 and 4.12. In each configuration, the system performs beautifully and exactly the way I want it to for about 30 seconds, then crashes to the Linux Mint login screen. It does not crash every time, but about 80% of the time; the other 20%, everything is beautiful and I have no issues whatsoever. My .xsession-errors file ends with these four lines consistently:
```
gnome-session-binary[32763]: WARNING: Application 'i3.desktop' failed to register before timeout
gnome-session-binary[32763]: CRITICAL: We failed, but the fail whale is dead. Sorry....
ICE default IO error handler doing an exit(), pid = 552, errno = 11
ICE default IO error handler doing an exit(), pid = 488, errno = 11
```
Any other warnings or errors I have found I researched and seem to be of no consequence. Let me know if you want the complete file anyway.

I took what @joehillen said and started gnome-settings-daemon with i3 and everything seems wonderful! Thank you so much for the workaround in the meantime! It does everything I want GNOME to do in i3.
